[project]
name = "multi-agent-trip-planner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lavish gupta", email = "lavish.gupta@ibm.com" }
]
requires-python = ">=3.10"
dependencies = []

[project.scripts]
multi-agent-trip-planner = "multi_agent_trip_planner:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
